import { Schema, model, Document, Types } from 'mongoose';

export type RestaurantCouponType =
  | 'percentage'
  | 'flat'
  | 'bogo'            // buy one get one
  | 'combo'
  | 'birthday'
  | 'anniversary'
  | 'festival'
  | 'first_visit'
  | 'welcome'
  | 'referral'
  | 'loyalty_redeem'; // generated from loyalty points

export type RestaurantCouponStatus = 'active' | 'expired' | 'paused' | 'depleted';

export interface IRestaurantCoupon extends Document {
  restaurantId: Types.ObjectId;
  code: string;
  name: string;
  description?: string;
  type: RestaurantCouponType;
  discountValue: number;         // percent or flat amount
  maxDiscountAmount?: number;    // cap for percentage coupons
  minOrderAmount: number;
  usageLimit: number;            // 0 = unlimited
  usageCount: number;
  perCustomerLimit: number;      // 0 = unlimited
  applicableCategories: Types.ObjectId[];
  applicableItems: Types.ObjectId[];

  // Targeting
  targetSegment?: string;        // 'all' | 'vip' | 'inactive' | custom segment name
  targetCustomerIds: Types.ObjectId[];  // specific customers (empty = all eligible)

  status: RestaurantCouponStatus;
  startDate: Date;
  endDate: Date;

  // Auto-generate config
  isAutoGenerated: boolean;
  autoTrigger?: string;          // 'birthday' | 'anniversary' | 'nth_order' | 'spend_milestone'

  isDeleted: boolean;
  deletedAt?: Date;
  createdBy?: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const restaurantCouponSchema = new Schema<IRestaurantCoupon>(
  {
    restaurantId: { type: Schema.Types.ObjectId, ref: 'Restaurant', required: true, index: true },
    code: { type: String, required: true, trim: true, uppercase: true },
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    type: {
      type: String,
      enum: ['percentage', 'flat', 'bogo', 'combo', 'birthday', 'anniversary',
             'festival', 'first_visit', 'welcome', 'referral', 'loyalty_redeem'],
      required: true,
    },
    discountValue: { type: Number, required: true, min: 0 },
    maxDiscountAmount: { type: Number, min: 0 },
    minOrderAmount: { type: Number, default: 0, min: 0 },
    usageLimit: { type: Number, default: 0, min: 0 },
    usageCount: { type: Number, default: 0, min: 0 },
    perCustomerLimit: { type: Number, default: 1, min: 0 },
    applicableCategories: [{ type: Schema.Types.ObjectId, ref: 'MenuCategory' }],
    applicableItems: [{ type: Schema.Types.ObjectId, ref: 'MenuItem' }],
    targetSegment: { type: String, trim: true },
    targetCustomerIds: [{ type: Schema.Types.ObjectId, ref: 'Customer' }],
    status: {
      type: String,
      enum: ['active', 'expired', 'paused', 'depleted'],
      default: 'active',
      index: true,
    },
    startDate: { type: Date, required: true },
    endDate: { type: Date, required: true, index: true },
    isAutoGenerated: { type: Boolean, default: false },
    autoTrigger: { type: String, trim: true },
    isDeleted: { type: Boolean, default: false, index: true },
    deletedAt: { type: Date },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

restaurantCouponSchema.index({ restaurantId: 1, code: 1 }, { unique: true });
restaurantCouponSchema.index({ restaurantId: 1, status: 1 });
restaurantCouponSchema.pre('find', function () { this.where({ isDeleted: false }); });
restaurantCouponSchema.pre('findOne', function () { this.where({ isDeleted: false }); });

export const RestaurantCoupon = model<IRestaurantCoupon>('RestaurantCoupon', restaurantCouponSchema);
